export enum Path {
  BACKUP = "/backup",
  CHANGE_PASSWORD = "/change_password",
  CONNECTION_FAILED = "/connection_failed",
  CONSOLE = "/console",
  DASHBOARD = "/dashboard",
  HOME = "/",
  INITIAL_SETUP = "/initial_setup",
  OVERVIEW = "/overview",
  SETTINGS = "/settings",
  TRADE = "/trade",
  TRADEHISTORY = "/tradehistory",
  WALLETS = "/wallets",
  LEARN = "/learn",
}
